### PR TITLE
docs: Fix comments and spacing

### PR DESCRIPTION
**Pull request by RichardLitt**
This basically copies the changes that were in samples/Tutorial/WhoIsIAm.py. However, on a much more relevant note than this small PR, I do not understand why these two files are different, or why one works and not the other. It seems like the tutorial file is more up to date; but what does IOCB not do, that it could be removed? I am curious.

### CODE REVIEW

**Comment by JoelBender** [comment]
These two applications started out the same!  The tutorial version takes advantage of the `who_is()` and `i_am()` functions that were added a while ago, but the non-tutorial version uses the `IOController` API like it should.  Because this sample generates unconfirmed requests that get completed as soon as they are processed (there is no waiting for an Ack) the `Application` silently ignores it.

I haven't looked at the applications in the Tutorial directory in quite a while, or the documentation for that matter :facepalm:, I think the right thing to do is to move the tutorial files into the regular samples directory so there's no longer a split brain (and there's only one overlapping application so it's not so bad) and make sure the documentation references the correct file(s).

I would normally squash/merge this into a new branch called something like `337-fix-tutorial` and then milestone it for the next release.  But may not.

**Comment by RichardLitt** [comment]
How does that look, Joel? Thanks for your clarity. Good to know I wasn't messing up when it wasn't responding!

**Comment by JoelBender** [comment]
I merged this into the `develop` branch.

**Comment by RichardLitt** [comment]
Sweet. Thank you!

**Pull request closed without merging**
