### PR TITLE
docs: spelling errors

### PR DESCRIPTION
**Pull request by RichardLitt**
Also removed whitespace. Can resubmit if that is unsatisfactory.

### CODE REVIEW

**Comment by JoelBender** [comment]
Thank you, I'm reviewing my git-fu on how to handle pull requests over on (gitter)[https://gitter.im/JoelBender/bacpypes] if you would like to join the conversation.

**Comment by RichardLitt** [comment]
Let me know if you want me to base this on another branch.

**Comment by JoelBender** [comment]
I merged this into the `develop` branch.

**Comment by RichardLitt** [comment]
Thank you!

**Pull request closed without merging**
