### PR TITLE
Decoding error with Delta Controllers (description)

### PR DESCRIPTION
**Pull request by ChristianTremblay**
This change a little how we handle decoding of character string to fix a bug moslty got from Delta Controllers that are syaing to be encoding with UTF-8 but use latin-1 encoding for the descriptions of the properties. Enclosed the decoding inside a try except block to catch real problems and give a chance to the “else” block that was there before, to be triggered, now inside the except block... Note that in the first attempt to decode, we try with UTF-8, if it fails... try with latin-1 and if it fails again, reraise the exception.

I think it’s probably a bug in their software, Windows based, that will not respect UTF-8 encoding all the time. Trying latin-1, for characters, seems an acceptable tweak to add robustness to bacpypes.

@JoelBender the “black” formatting has been triggered. This explain the “formatting being different” I’ve started using this module as a pre-commit... Honestly, I like “not having” to bother about formatting and letting it do the job.
https://github.com/ambv/black
I just didn’t think shutting it off before committing... 

See line 968 for real changes

### CODE REVIEW

**Comment by ChristianTremblay** [comment]
Did I say....refers to issue #193

**Comment by JoelBender** [comment]
Do you have some sample byte strings that can trigger this behavior so I can add them to the test cases?  I would like to make sure the problem can be reproduced with Python 2.7 and fixed in a similar way.

**Comment by ChristianTremblay** [comment]
b’Some description with a temperature of \xb0F’

A string-like I worked with. From a random controller found somewhere ;-)

\xb0 is the degree sign

Maybe people havin the trouble in issue 193 could also test and give us the
strings that fail

Le dim. 3 févr. 2019 à 23:10, Joel Bender <notifications@github.com> a
écrit :

**Comment by JoelBender** [comment]
I started a new branch `241-string-decoding-error` because I couldn't hack my way through the other one.  I added the fallback code and the 3+ tests pass but the 2.7 test fails.  Here is some sample code:
```python
from bacpypes.debugging import btox, xtob
from bacpypes.primitivedata import Tag, CharacterString

b = xtob('00b0') # degree symbol
tag = Tag(Tag.applicationTagClass, Tag.characterStringAppTag, len(b), b)
obj = CharacterString()
obj.decode(tag)

s = obj.value

print("%s %s %r" % (type(s), s, s))
```
And running on Python 2.7 looks like this:
```
$ python2.7 a.py 
<type 'str'> \xb0 '\\xb0'
```
And running on Python 3.5 looks like this:
```
$ python3.6 a.py 
<class 'str'> ° '°'
```
I'm not sure what to do next for the Python 2.7 tests, I would guess that you want the fallback decoding to return the "natural" UTF-8 encoded string '\xc2\xb0' rather than returning a unicode string which is a headache.

**Comment by ChristianTremblay** [comment]
You know me, I’m more inclined to deprecate 2.7 :-)
The most important for me though is to prevent an exception to occur. In its actual form, if we meet the controllers which badly implement the encoding, bacpypes fails. And it is very hard to prevent this in external code. I really think it’s better if bacpypes deals with this internally. In python 3, we can hack this and correct the bad implementation this is perfect. 

In python 2, we could start by outputting the code string. Even if it’s not cute. At least it won’t raise an exception and make the app fail. I’ll ask @sjlongland if he has an idea. He is pretty good with python 2.

**Comment by sjlongland** [comment]
Yeah, even at work though, I'm starting to work towards pushing Python 2.x stuff into the bit bucket (and I don't mean Atlassian's git repository).

There are a lot of people who don't understand byte encodings… and thus will mix-up [Latin1](https://en.wikipedia.org/wiki/ISO/IEC_8859-1), [UTF-8](https://en.wikipedia.org/wiki/UTF-8), [GB18030](https://en.wikipedia.org/wiki/GB_18030) and just about anything else.  Some will decode, but you'll get [mojibake](https://en.wikipedia.org/wiki/Mojibake) unless it happens to be the correct code.

```
>>> raw=b'Some description with a temperature of \xb0F'
>>> print raw.decode('gb18030')
Some description with a temperature of 癋
>>> print raw.decode('latin1')
Some description with a temperature of °F
>>> print raw.decode('latin2')
Some description with a temperature of °F
```

If you are certain it is *supposed* to be UTF-8, you could try `errors='ignore'` or `errors='replace'` which will at least stop Python from barfing on the string.  There's no way of knowing if an arbitrary string is "correct".

**Comment by sjlongland** [comment]
For what it's worth, lots of people get this wrong… this is an example that shows up on my phone's music player from time to time:
```
>>> print u'Ça Plane Pour Moi'.encode('UTF-8').decode('gb18030')
脟a Plane Pour Moi
```

**Comment by ChristianTremblay** [comment]
Plastic Bertrand

Classique ;-)

Le jeu. 25 avr. 2019 à 16:36, Stuart Longland <notifications@github.com> a
écrit :

**Comment by JoelBender** [comment]
The branch is updated and the new test passes both Python 2 and Python 3.  Unfortunately it means that the a CharacterString object cannot round-trip successfully, but I don't think it can be helped.  If this passes your _no barf_ real world tests then I'll roll this into `master` branch and release it.

**Comment by sjlongland** [comment]
To be honest, I'm of the opinion, garbage in, garbage out.  Not sure what the ASHRAE specs say regarding character encoding, but I'd think in this day and age, any modern standard should be looking to UTF-8, and I'd be looking to use that standard in the absence of others in the name of interoperability.

We should gracefully try to handle the garbage without crashing, being able to round-trip data without invalid characters getting replaced or dropped is not guaranteed.  If this commit achieves this, that's good enough.  So long as it round-trips properly formed UTF-8 strings, I think that's as much as can be expected of us.

**Comment by ChristianTremblay** [comment]
I think I have something interesting : 
```
import unicodedata

# [goto line where we normalize]
try:
    if self.strEncoding == 0:
        try:
            udata = self.strValue.decode(‘utf_8’)
            self.value = str(udata.encode(‘ascii’, ‘backslashreplace’)
        except UnicodeDecodeError:
            try:
                udata = unicode(str(self.strValue),’latin_1’)
                norm = unicodedata.normalize(‘NFKD’,udata)
                self.value = str(norm.encode(‘ascii’,’ignore’))
            except UnicodeDecodeError:
                raise
    # Continue with other string encoding
    except UnicodeDecodeError:
        self.value = ‘### unknown encoding: %d ###’ % (self.strEncoding)
```

The result is very interesting as the normalization will replace know characters with their non-accentuated version. Example : état will become etat 
For weird non convertable characters, they will be ignored

10°F will become 10F 

This gives us something readable.
Unicodedata is part of the standard library, no external dependency.

Now the test must be a little different for python 2.7 as degree sign disappear. But I’m pretty sure we can find a way...

**Comment by ChristianTremblay** [comment]
Moved here : https://github.com/JoelBender/bacpypes/pull/269

**Pull request closed without merging**
