### PR TITLE
Out of service | Change mutability

### PR DESCRIPTION
**Pull request by ChristianTremblay**
Some object properties must be writable if the out_of_service property is True.

This PR present an attempt to make that work at the object level, allowing a property to be mutable when outOfService is True.

The complete object List would need to be modified.
I've implemented the change on the AnalogInputObject only adding this new parameter : 

```
@register_object_type
class AnalogInputObject(Object):
    objectType = 'analogInput'
    properties = \
        [ ReadableProperty('presentValue', Real, writable_if_oos=True)
        , OptionalProperty('deviceType', CharacterString)
        , ReadableProperty('statusFlags', StatusFlags)
        , ReadableProperty('eventState', EventState)
        , OptionalProperty('reliability', Reliability, writable_if_oos=True)
    #[...]
```

### CODE REVIEW

**Comment by JoelBender** [comment]
I'm concerned about loading up the core `Property` class with more options and changing the mutability of an object on the fly means that the class name like `WritableProperty` no longer matches its behavior.  Other object types have more conditions in the footnotes, like the Analog Value Object states:

> (4)If Present_Value is commandable, then it is required to be writable. This property is required to be writable when Out_Of_Service is TRUE.

There is the `CommandableMixin.py` sample code that is going to get moved into the `bacpypes.local.cmd` module so maybe this behavior can be incorporated in a similar way.

**Comment by ChristianTremblay** [comment]
Those who never try, never fail. :-)

Let me know if I can help. I understand that the out of service behaviour is exceptional in some way and this make categorization of the PV somewhat weird. It is readable but ...

**Comment by Mathadon** [comment]
Hi, is my interpretation of this post correct that bacpypes cannot currently write the OutOfService property? Thank you! Will this be supported in bacpypes3?

**Comment by ChristianTremblay** [comment]
This was related to local objects to a bacpypes instances (objects "served" by bacpypes)

Writing to out of service to bacnet devices is supported.

**Pull request closed without merging**
