### PR TITLE
developing with bacpypes?

### PR DESCRIPTION
**Pull request by kjlockhart**
First, sorry if this is not the best way to reach you regarding your Github project 'bacpypes'.  Please advise me with your preferred method.
[BTW: Where must be a way to 'contact author' via Github but I couldn't find it.]

My questions:

I am trying to develop several BACnet client applications.  One will discover the analog & binary I/O objects on a set of BACnet controllers and periodically poll for their presentValues.  The second will discover the Trend_Log objects on a set of BACnet controllers and periodically read the trend contents (via ReadRange).

I have worked through all the samples,tutorials, and documentation.  But apparently several fundamental concepts are eluding me.  The samples are all async event-driven programs that expect user input via the CmdConsole.  They all derive from BIPSimpleApplication.  I see bacpypes.app also contains classes: Application, ApplicationIOController, BIPForeignApplication, BIPNetworkApplication, plus a DeviceInfoCache.  I can find no documentation on any of the these or when they should be used, or for what purpose.

I am trying to get started - with a very simple goal in mind.  But I am at a complete loss how to get started; how to interface with bacpypes in the simplest, most direct manner.

I want to write a program that:
- needs no user input.
- uses bacpypes to read object and trend data from a set of (known, or discoverable) controllers.
- acts as a BACnet client-only.  
- No BACnet devices will ask it for information.  It provides no BACnet server functionality.
- runs periodically, in a stand-alone automated fashion.  i.e. it is a batch process started via cron.
- doesn't need threads.  
- ideally it will startup, read a list of object references from a local file, will loop through the references making ReadPropertyMultiple & ReadRange requests, parse the responses, save the results, and exit.  [no fuss, no muss, no complex stuff. 😊]

Where could I find a similar client-only program to use as a starting point?

Thanks.

### CODE REVIEW

**Comment by JoelBender** [comment]
I received your email and it's probably easier to discuss the specifics of this with you there, the [developers mailing list](https://sourceforge.net/p/bacpypes/mailman/bacpypes-developers/) is still active even though the project has moved here.

**Comment by ChristianTremblay** [comment]
As a starting point, looking at the things you want to do, I can suggest you have a look to https://github.com/ChristianTremblay/BAC0

You could then build your script easily using :

import BAC0
bacnet = BAC0.connect()

device = BAC0.device(address, devID, bacnet)
# Example
# dev = BAC0.device('2:5', 5005, bacnet)

Then retrieve the variables you want 
temp=device['VARIABLENAME']

# Example
# disch_air = device['DA-T']

**Comment by ChristianTremblay** [comment]
If it does completely fit your need, you will be able to start from there and pass directly to bacpypes to get something less general and more concise.

**Comment by kjlockhart** [comment]
Thank you.  It definitely seems promising.


FYI: pypi - BAC0 0.99.82 fails to install.

---------

Collecting BAC0
  Downloading BAC0-0.99.82.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-SrbRJU/BAC0/setup.py", line 5, in <module>
        import BAC0.infos as infos
      File "BAC0/__init__.py", line 4, in <module>
        from . import core
      File "BAC0/core/__init__.py", line 3, in <module>
        from . import app
      File "BAC0/core/app/__init__.py", line 3, in <module>
        from . import ScriptApplication
      File "BAC0/core/app/ScriptApplication.py", line 33, in <module>
        from ..functions.debug import log_debug
      File "BAC0/core/functions/__init__.py", line 3, in <module>
        from . import discoverPoints
      File "BAC0/core/functions/discoverPoints.py", line 11, in <module>
        from ..devices.Points import EnumPoint, BooleanPoint, NumericPoint
      File "BAC0/core/devices/__init__.py", line 3, in <module>
        from . import Device
      File "BAC0/core/devices/Device.py", line 90
        def __init__(self, address, device_id, network, *, poll=10, from_backup = None, segmentation_supported = True):
                                                         ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-SrbRJU/BAC0/


---------


As do many of the other versions(0.99.7-0.99.2).  I did get 0.99.72 to install.

Looks like a python2 vs. python3 issue.  Name change re: queue

----------

Collecting BAC0==0.99.3
  Downloading BAC0-0.99.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-0ooeZL/BAC0/setup.py", line 5, in <module>
        from BAC0 import infos as infos
      File "BAC0/__init__.py", line 3, in <module>
        from . import core
      File "BAC0/core/__init__.py", line 3, in <module>
        from . import app
      File "BAC0/core/app/__init__.py", line 3, in <module>
        from . import ScriptApplication
      File "BAC0/core/app/ScriptApplication.py", line 40, in <module>
        from queue import Queue
    ImportError: No module named queue
----------


________________________________

**Comment by ChristianTremblay** [comment]
I should have told that I concentrated all my efforts on Python 3.

**Comment by kjlockhart** [comment]
ah yes.  makes sense.
I will do likewise, and ensure I am only using Python 3 tools and modules.
After sending the email, I tried using Pip3/Python 3 and things went a lot smoother.




________________________________

**Comment by JoelBender** [comment]
Closing this pull request.

**Pull request closed without merging**
