### PR TITLE
Issue11

### PR DESCRIPTION
**Pull request by ChristianTremblay**
Trying to run nosetests on py34...
Still 7 failures but errors are gone

### CODE REVIEW

**Comment by JoelBender** [comment]
I found the additional `__lt__` function you added, and the delta parameter was added after I synchronized the changes in the py27 `bacpypes/tasks.py` and py34.

The other more significant problem was that the syntax for the singleton metaclass changed from being a special named attribute `__metaclass__` to a keyword attribute in the class decoration.  So the tests were failing because the TimeMachine wasn't being created correctly.

I was confused about the massive number of differences listed in the pull request, but then I keyed in on the reference to the master branch.  There weren't that many changes that you had made from the `issue-11` branch, alleviating my panic.

The `issue-11` tests now pass in py27 and py34, but I'm not ready to merge this into the master.  Please pull an updated version of the `issue-11` branch and re-run your tests.

**Comment by ChristianTremblay** [comment]
I promise I'll be good with Git one day ! There must be something I did wrong...

Learning everyday... 

I pulled issue-11 (fetch in fact...tehn switch) and every tests pass no problem.
I also saw that you used id instead of taskTime in the __lt__ function. Is there any risk of using that ? I read somewhere that two class may have the same id in some cases (overlapping of some kind with respect to garbage collector... ) This question is strictly motivated by curiosity !

**Comment by JoelBender** [comment]
I wanted to use some attribute/property of an object that was unique, and I had no idea that two classes could have the same id.  At least in this case I'm dealing with the identities of objects and not classes.  I'll have to look into your question more closely at some point.

**Comment by JoelBender** [comment]
I believe that all of the changes for this issue have been merged into *stage* and then *master* and released.  I'm going to close this issue, feel free to double check what was done and reopen it.

**Pull request closed without merging**
